#Notification Service Yaml file

server:
  port: 9000

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
    topic:
      user-random_topic: user-random-topic


