#Notification Service Yaml file

server:
  port: 9000

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      properties:
        spring.json:
          trusted.packages: com.kafka_project.*
    topic:
      user-random_topic: user-random-topic
      user-created_topic: user_created-topic


